version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.13"
  jobs:
    post_checkout:
      - "[ ${READTHEDOCS_VERSION_TYPE} = external ] || exit 183"
      - git ls-remote --tags --sort=version:refname 2>&- | awk "END{printf \"+%s:%s\\n\",\$2,\$2}" | git fetch origin --depth=300
      - git fetch origin --depth=300 --update-shallow
      - git describe --tags --long --dirty
    post_install:
      - python -m pip install --upgrade --upgrade-strategy=eager -e . --group docs

sphinx:
  configuration: docs/conf.py
