codecov:
  notify:
    require_ci_to_pass: true
    # wait until at least one linux and one windows build has succeeded (see the test job's build matrix)
    after_n_builds: 6
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 50.0
  - 100.0
  round: down
  status:
    changes: false
    patch: false
    project:
      default:
        target: 30
