name: Plugin issue
description: One of Streamlink's plugins doesn't work correctly
title: "plugins.plugin-name-here: A very brief summary of what's broken"
labels:
  - plugin issue
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reporting a plugin issue!

        Plugin issues describe broken functionality within a plugin's code base, eg. the streaming site has made breaking changes, streams don't get resolved correctly, or authentication has stopped working, etc.

        **DON'T IGNORE this template and fill in all the required details.**
        **Issues that don't adhere to our request will be closed and ignored.**
        This is because analyzing bugs, issues or requests without proper details and log output is harder than necessary.
        Low quality and low effort issues are noise and steal the time of the maintainers and contributors.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: This is a plugin issue and not a different kind of issue
          required: true
        - label: "[I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)"
          required: true
        - label: "[I have checked the list of open and recently closed plugin issues](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+issue%22)"
          required: true
        - label: "[I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)"
          required: true
  - type: dropdown
    attributes:
      label: Streamlink version
      description: |
        [Only the **latest stable release** or **latest build from the master branch** will be accepted.](https://streamlink.github.io/install.html)
        The mandatory debug log down below still needs to include the explicit version string.
      options:
        - Latest stable release
        - Latest build from the master branch
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Explain the plugin issue as thoroughly as you can.
        Please also provide the exact steps for reproducing the issue, eg. a list of input URLs.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Debug log
      description: |
        DEBUG LOG OUTPUT IS REQUIRED for plugin issues!
        INCLUDE THE ENTIRE COMMAND LINE and make sure to **remove usernames and passwords**

        Use the [`--loglevel debug`](https://streamlink.github.io/latest/cli.html#cmdoption-loglevel) parameter and avoid using parameters which suppress log output.
        Debug log includes important details about your platform. Don't remove it.

        If the log output is too long and repetitive parts can't be truncated, or if you have multiple log outputs to share, please post a link to a [GitHub gist](https://gist.github.com/) with the log output instead.
      placeholder: |
        Don't post screenshots of the log output and instead copy the text from your terminal application.

        The content will be rendered as code block.
      render: text
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Before submitting

        Make sure that you have
        - properly filled in the title of this plugin issue
        - checked the rendered text previews to avoid unnecessary formatting errors

        ----

        [Love Streamlink? Please consider supporting our collective. Thanks!](https://opencollective.com/streamlink/donate)
