name: 🐛 Bug Report
description: A core functionality of Streamlink is broken.
title: "A very brief summary of what's broken"
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for reporting a bug!

        > [!IMPORTANT]
        > **What is a bug report?**
        > Bugs are the result of broken functionality within Streamlink's main code base.
        > This can be a bug in the command-line interface, the various streaming protocol implementations, or the core Streamlink APIs, etc.
        >
        > Use the [plugin issue template](https://github.com/streamlink/streamlink/issues/new/choose) if your report is about a broken plugin.
        > [See the list of the available plugins here.](https://streamlink.github.io/plugins.html)

        > [!CAUTION]
        > **DO NOT IGNORE this template**
        > Please fill in all the required details and don't skip any parts.
        > Issues that don't adhere to our request will be closed and ignored immediately.
        >
        > This is because analyzing bugs, issues or requests without proper details and log output is harder than necessary.
        > Low quality and low effort issues are noise and steal the time of the maintainers and contributors.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: This is a bug report and not [a different kind of issue](https://github.com/streamlink/streamlink/issues/new/choose)
          required: true
        - label: "[I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)"
          required: true
        - label: "[I have checked the list of open and recently closed bug reports](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22bug%22)"
          required: true
        - label: "[I have checked the commit log of the master branch](https://github.com/streamlink/streamlink/commits/master)"
          required: true
  - type: checkboxes
    attributes:
      label: Collaboration
      options:
        - label: "[I will provide feedback should a pull request be opened with a fix for the problem](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback)"
          required: true
  - type: input
    attributes:
      label: Streamlink version
      description: |
        [Only the **latest stable release or newer** will be accepted!](https://streamlink.github.io/install.html)

        Post the **exact output** of [`streamlink --no-config --version`](https://streamlink.github.io/cli.html#cmdoption-version).
        Issues without a valid version string will be closed and ignored immediately.

        Before you continue, check the [list of recent releases](https://streamlink.github.io/changelog.html) or run `streamlink --no-config --version-check`.

        The mandatory debug/trace log down below still needs to include the explicit version string.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Explain the bug as thoroughly as you can.
        Please also provide the exact steps for reproducing the issue.

        Any kind of packaging issue except for Streamlink's own sdist/bdist packages on PyPI does not belong here and should be reported on the respecting issue tracker or to the respecting third-party packager.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Debug/trace log
      description: |
        **DEBUG/TRACE LOG OUTPUT IS REQUIRED for bug reports!**

        INCLUDE THE ENTIRE COMMAND LINE and make sure to **remove all sensitive data from the entire log output, like usernames, passwords, cookies, etc!**
        Issues that don't include a **full debug/trace log** will be closed and ignored immediately.

        Use the [`--loglevel=debug` / `--loglevel=trace`](https://streamlink.github.io/latest/cli.html#cmdoption-loglevel) parameter and avoid using parameters which suppress log output.
        Debug/trace log includes important details about the used Python environment. **Don't remove it.**

        If the log output is too long and repetitive parts can't be truncated, or if you have multiple log outputs to share, then please post a link to a [GitHub gist](https://gist.github.com/) with the log output instead.

        **DO NOT post screenshots of the log output and instead copy the text from your terminal application.**
      placeholder: |
        The content will be rendered as code block.
      render: text
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > **Before submitting**
        >
        > Make sure that you have
        > - [ ] properly filled in the title of this bug report (at the very top of this page)
        > - [ ] checked the rendered text previews to avoid unnecessary formatting errors

        ----

        [❤️ Love Streamlink? Please consider supporting the project maintainers. Thanks! ❤️](https://streamlink.github.io/latest/support.html)
