name: 🧩 Plugin request
description: Discuss adding a new plugin to Streamlink.
title: "Name of the website / streaming provider"
labels:
  - plugin request
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for requesting a plugin!

        [READ THE PLUGIN REQUEST REQUIREMENTS IN THE CONTRIBUTION GUIDELINES BEFORE POSTING!](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#plugin-requests)

        ----

        **DON'T IGNORE this template and fill in all the required details.**
        **Issues that don't adhere to our request will be closed and ignored.**
        This is because analyzing bugs, issues or requests without proper details and log output is harder than necessary.
        Low quality and low effort issues are noise and steal the time of the maintainers and contributors.
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: This is a plugin request and not a different kind of issue
          required: true
        - label: "[I have read the contribution guidelines](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#contributing-to-streamlink)"
          required: true
        - label: "[I have checked the list of open and recently closed plugin requests](https://github.com/streamlink/streamlink/issues?q=is%3Aissue+label%3A%22plugin+request%22)"
          required: true
  - type: textarea
    attributes:
      label: Description
      description: |
        Explain the plugin and site as clearly as you can according to the plugin request guidelines. For example:

        - What is the site about?
        - Who is it run by?
        - What kind of content does it provide?
        - Are there any access restrictions like logins or region checks?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Input URLs
      description: |
        Please provide a list of example input URLs.

        **DO NOT post screenshots of the site or your web browser.**
      placeholder: |
        1. ...
        2. ...
        3. ...
        etc.
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ### Before submitting

        Make sure that you have
        - [ ] properly filled in the title of this plugin request (at the very top of this page)
        - [ ] checked the rendered text previews to avoid unnecessary formatting errors

        Please [don't forget to provide feedback](https://github.com/streamlink/streamlink/blob/master/CONTRIBUTING.md#pull-request-feedback) once a pull request gets submitted for adding the new plugin.

        ----

        [❤️ Love Streamlink? Please consider supporting the project maintainers. Thanks! ❤️](https://streamlink.github.io/latest/donate.html)
