# DO NOT EDIT THIS FILE!
#
# This file is generated from the CDP specification. If you need to make
# changes, edit the generator and regenerate all modules.
#
# CDP version: v0.0.1510116

from __future__ import annotations

from typing import TYPE_CHECKING, Any, TypeAlias, cast


if TYPE_CHECKING:
    from collections.abc import MutableMapping

    try:
        from typing import Self  # type: ignore[attr-defined]
    except ImportError:
        from typing_extensions import Self


T_JSON_DICT: TypeAlias = dict[str, Any]
_event_parsers: MutableMapping[str, type[CDPEvent]] = {}


class _CDPEventMeta(type):
    def __new__(
        cls,
        name,
        bases,
        namespace,
        event: str | None = None,
        **kwargs,
    ) -> _CDPEventMeta:
        obj = super().__new__(cls, name, bases, namespace, **kwargs)
        if event is not None:
            _event_parsers[event] = cast("type[CDPEvent]", obj)

        return obj


class CDPEvent(metaclass=_CDPEventMeta):
    @classmethod
    def from_json(cls, json: T_JSON_DICT) -> Self: ...  # pragma: no cover


def parse_json_event(json: T_JSON_DICT) -> CDPEvent:
    """Parse a JSON dictionary into a CDP event."""
    return _event_parsers[json["method"]].from_json(json["params"])
