#!/bin/bash

# This file fill generate and output all authors whom have contributed to the project
# to the root dir AUTHORS file.

if [ ! -f AUTHORS ]; then
  echo "AUTHORS file not found. Are you not in the root directory?"
else
  echo -e "This AUTHORS file is generated by ./script/authors.sh\nThank you to everyone whom has contributed to streamlink / livestreamer.\n\n" > AUTHORS
  git log --format='%aN' | sort -u >> AUTHORS
fi
