name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - "**"

jobs:
  documentation:
    name: Build and deploy
    if: github.repository == 'streamlink/streamlink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: |
          git ls-remote --tags --sort=version:refname 2>&- | awk 'END{printf "+%s:%s\n",$2,$2}' | git fetch origin --depth=300
          git fetch origin --depth=300 --update-shallow
          git describe --tags --long --dirty
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Build
        run: uv run --frozen --group docs make --directory=docs html
      - name: Deploy
        env:
          DOCS_DEPLOY_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
        run: ./script/deploy-docs.sh
