name: Documentation

on:
  push:
    branches:
      - master
    tags:
      - "**"

concurrency:
  group: docs-deployment
  cancel-in-progress: false

jobs:
  documentation:
    name: Build and deploy
    if: github.repository == 'streamlink/streamlink'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 300
      - name: Fetch tags
        run: ./.github/workflows/scripts/fetch-tags.sh
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          prune-cache: true
      - name: Build
        run: uv run --frozen --group docs make --directory=docs html
      - name: Deploy
        env:
          DOCS_DEPLOY_TOKEN: ${{ secrets.DOCS_DEPLOY_TOKEN }}
        run: ./script/deploy-docs.sh
