name: Lint

on:
  pull_request: {}

jobs:
  files:
    name: Files
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: File permissions
        if: ${{ !cancelled() }}
        run: "! grep -Ev '^644' <(git ls-files src/ tests/ | xargs stat '--format=%a %n')"
      - name: File encodings
        if: ${{ !cancelled() }}
        run: "! grep -E -e 'UTF-[^8]' -e 'UTF-[^ ]+ \\(with BOM\\)' <(git ls-files src/ tests/ | xargs stat '--format=%a %n')"
      - name: Line terminators
        if: ${{ !cancelled() }}
        run: "! grep 'with CRLF line terminators' <(git ls-files | file -nNf-)"
      - name: No unicode bidirectional control characters
        if: ${{ !cancelled() }}
        run: "! git grep -EIn $'[\\u2066\\u2067\\u2068\\u2069\\u202A\\u202B\\u202C\\u202D\\u202E]'"

  style:
    name: Code style
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: ruff check
        if: ${{ !cancelled() }}
        run: uv run --frozen --group lint ruff check .
      - name: ruff format
        if: ${{ !cancelled() }}
        run: uv run --frozen --group lint ruff format --diff .

  typing:
    name: Typing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: ty
        if: ${{ !cancelled() }}
        run: uv run --frozen --group typing ty check
      - name: mypy
        if: ${{ !cancelled() }}
        run: uv run --frozen --group typing mypy --no-incremental
      - name: mypy docs
        if: ${{ !cancelled() }}
        run: uv run --frozen --group typing mypy --python-version=3.12 --no-incremental docs
